version: '3'
services:
   db:
      image: postgres:11.4
      container_name: aact
      restart: always
      ports:
         - 5432:5432
      environment:
         - POSTGRES_USER=clinwiki
         - POSTGRES_PASSWORD=JQIhi3AGyBwl
      volumes:
         - aact-data:/var/lib/postgresq/data
         - .:/scripts/
volumes:
   aact-data:
